### ISSUE TITLE
Lock() should use fcntl.lockf()

### ISSUE THREAD

**Issue by Minoru** [lenormf/newsboat-sendmail#1]
Hey there! Nice script.

I didn't actually run it, but I read through the code, and one thing stuck out to me:

https://github.com/lenormf/newsboat-sendmail/blob/5fef7d2e8e23d23970bf0e02b6fad7d0f10b31eb/newsboat-sendmail.py#L284-L298

This snippet creates a file, but doesn't lock it. [Newsboat uses `lockf()` for that](https://github.com/newsboat/newsboat/blob/73572d8335652759c0f21a1d30f6916fd23d67d2/src/fslock.cpp#L45-L70). Since the `Lock()` doesn't call `lockf()`, Newsboat will succeed in taking its own lock, and will simply overwrite the file with its own PID.

I believe calling [`fcntl.lockf()`](https://docs.python.org/3/library/fcntl.html#fcntl.lockf) should make this script compatible with Newsboat.

**Comment by lenormf** [comment]
Thanks for reviewing the code!

I didn't look at Newsboat's code, I wrote all my code based on assumptions. And I assumed Newsboat wouldn't run if a lock-file had already been created :)

I'll look into addressing the issues you found.
