### ISSUE TITLE
Script should read path to cache file from the config

### ISSUE THREAD

**Issue by Minoru** [lenormf/newsboat-sendmail#2]
The names of the cache file and the lock files [are hard-coded right now](https://github.com/lenormf/newsboat-sendmail/blob/5fef7d2e8e23d23970bf0e02b6fad7d0f10b31eb/newsboat-sendmail.py#L64-L65). Newsboat lets users change the location of the cache file via [`cache-file` setting](https://newsboat.org/releases/2.19/docs/newsboat.html#cache-file) in the config file. The lock file follows (it's [a path to the cache file plus ".lock" suffix](https://github.com/newsboat/newsboat/blob/73572d8335652759c0f21a1d30f6916fd23d67d2/rust/libnewsboat/src/configpaths.rs#L270)).

For best compatibility, this script should read the config file, find a line starting with `cache-file`, and use the value as a path to the cache file, adjusting the lock file path accordingly.

**Comment by lenormf** [comment]
I was hoping to avoid having to parse the configuration file… I'll probably have to get around to doing it.

**Comment by Minoru** [comment]
Oh yeah, I can understand the reluctance. Newsboat parses its config [with this giant function](https://github.com/newsboat/newsboat/blob/73572d8335652759c0f21a1d30f6916fd23d67d2/src/utils.cpp#L86-L191), so you're definitely in for a treat. Watch out for comments (they start with `#`), double quotes, and note that hashes inside double quotes don't actually start comments! [Newsboat has a decent test suite for that function](https://github.com/newsboat/newsboat/blob/73572d8335652759c0f21a1d30f6916fd23d67d2/test/utils.cpp#L81-L260), so if you port that, you can be pretty confident that your implementation is in line with Newsboat's.

**Comment by lenormf** [comment]
I managed to get something going with the built-in INI parser:

https://github.com/lenormf/newsboat-sendmail/blob/aa629b9d7767abf761c9fd61b677d43f77912f3f/newsboat-sendmail.py#L63-L102

It's probably not very robust, but good enough until a user needs a fully-fledged parser.

Thanks again for reviewing the code, let me know if you find other bugs/improvements!
