### ISSUE TITLE
parsing config file produces errors

### ISSUE THREAD

**Issue by nedson** [lenormf/newsboat-sendmail#4]
When I issue newsboat-sendmail.py -d -n I receive this error:

[2020-09-15 13:45:15,739][INFO]: dry-run mode enabled, emails will not be sent, the database will not be modified, and the commands that would otherwise modify it will be printed
[2020-09-15 13:45:15,741][INFO]: loading the Newsboat configuration file
[2020-09-15 13:45:15,745][ERROR]: unable to parse configuration file: While reading from '<string>' [line 19]: option 'unbind-key' in section 'DEFAULT' already exists

I saw the note about parsing the ~/.config/newsboat/config file to find "cache-file". I didn't have "cache-file" set, so I added:

cache-file "~/.config/newsboat/cache.db" 

I am still receiving the same error. When parsed it trips on my custom keybindings.

**Comment by lenormf** [comment]
Thanks for the report.

Could you please share what keybindings are making the parser fail?

**Comment by nedson** [comment]
Hello,
Here is my config:  https://dpaste.com/FPYXAU8QN

Is the purpose of the parsing of the newsboat config to find the location of the cache.db? If so, could you just include that as a variable in sendmail.cfg?

**Comment by lenormf** [comment]
Thanks!

Yes the configuration is parsed solely to get a non-standard cache path, configured by the user. I'd rather not make this option redundant by declaring it in `sendmail.cfg` as well, so I need to parse the file.

I thought I got away with it by using an INI parser, but apparently not. I will look into this.

**Comment by lenormf** [comment]
I pushed a fix, could you please let me know if you find any more issues after applying it? If not, I will release v2.2.

The patch is simple:

```diff
diff --git a/newsboat-sendmail.py b/newsboat-sendmail.py
index 80bad80..0dcd471 100755
--- a/newsboat-sendmail.py
+++ b/newsboat-sendmail.py
@@ -64,6 +64,7 @@ class NewsboatSendmailConfig(configparser.ConfigParser):
 class NewsboatConfig:
     def __init__(self, path):
         self._config = configparser.ConfigParser(
+            strict=False,
             delimiters=(' ', '\t'),
             comment_prefixes=('#'),
             converters={
```
